import './global.css'
import localFont from 'next/font/local'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
//
//
// const myFont = localFont({
//   src: '/pobeda-regular.ttf',
//   display: 'pobeda',
// })
const myFont = localFont({
  src: '/pobeda-regular.ttf',
  display: 'swap'
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={myFont.className}>
      <body>{children}</body>
    </html>
  )
}
